stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - echo "Compilando..."
    - make build
test:
  stage: test
  script:
    - echo "Ejecutando pruebas..."
    - make test
deploy:
  stage: deploy
  script:
    - echo "Desplegando..."
    - make deploy
  environment:
    name: production
